server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ols?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: Aa941211

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl