server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://172.17.49.24:3306/ols?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: Aa941211