server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://34.80.79.144:3306/ols?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: Aa941211